name: climaf
channels:
  - pypi
  - conda-forge
dependencies:
  - cdo
  - nco
  - ncl
  - ncview
  - python=3
  - ipython
  - exiv2
  - latexcodec
  - pyproj
  - proj
  - geocat-viz
  - pip
  - pip:
          - netCDF4
          - numpy
          - sphinx
          - cftime
          - natsort
          - pyyaml
          - matplotlib
          - Cython
          - Cartopy
          - python-dateutil
          - pdflatex
          - dask
          - xarray
          - coverage
