#!/usr/bin/env python
# -*- coding: utf-8 -*-

from setuptools import find_packages
from setuptools import setup
import sys
import os


sys.path.append(os.path.dirname(os.path.abspath(__file__)))

version = __import__('climaf').version
description = 'CliMAF: a Climate Model Assessment Framework.'
long_description = (
    open('README.rst').read()
)

requires = [line.strip() for line in open('requirements.txt')]

classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Science/Research',
    'Operating System :: MacOS :: MacOS X',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX',
    'Programming Language :: Python',
    'Topic :: Scientific/Engineering :: Atmospheric Science',
    # 'License :: CeCILL-C Free Software License Agreement (CECILL-C)'
]

setup(name='climaf',
      version=version,
      description=description,
      long_description=long_description,
      classifiers=classifiers,
      keywords='python climate model',
      author='Stéphane Sénési',
      author_email="",
      url='https://github.com/rigoudyg/climaf',
      license="CeCILL-C license",
      packages=find_packages(),
      include_package_data=True,
      install_requires=requires,
      data_files=[
          "examples/data/AMIPV6ALB2G/A/AMIPV6ALB2GPL1980.nc",
          "examples/data/AMIPV6ALB2G/A/AMIPV6ALB2GPL1981.nc",
          "examples/data/AMIPV6ALB2G/L/AMIPV6ALB2GSFX1980.nc",
          "examples/data/AMIPV6ALB2G/L/AMIPV6ALB2GSFX1981.nc",
          "examples/data/NPv3.1ada_SE_1982_1991_1M_ua_pres.nc",
          "examples/data/tas_Amon_CNRM-CM5_historical_r1i1p1_185001-185212.nc",
          "examples/Adding_access_to_my_own_data.html",
          "examples/Adding_access_to_my_own_data.ipynb",
          "examples/ann_cycle.py",
          "examples/atlasoce.py",
          "examples/ATourOfCliMAF.html",
          "examples/ATourOfCliMAF.ipynb",
          "examples/basic_oce.py",
          "examples/Basis_of_CliMAF_data_access_at_CLIMERI.html",
          "examples/Basis_of_CliMAF_data_access_at_CLIMERI.ipynb",
          "examples/cdftools.py",
          "examples/cdftools_multivar.py",
          "examples/cdftransport.py",
          "examples/clean_cache.py",
          "examples/CliMAF_in_a_nutshell.html",
          "examples/CliMAF_in_a_nutshell.ipynb",
          "examples/CLIMERI_Quick_demo_CMIP_data_access_20181119.html",
          "examples/CLIMERI_Quick_demo_CMIP_data_access_20181119.ipynb",
          "examples/CMIP6_analysis_with_CliMAF.html",
          "examples/CMIP6_analysis_with_CliMAF.ipynb",
          "examples/CORDEX_ensembles_analysis_with_CliMAF.html",
          "examples/CORDEX_ensembles_analysis_with_CliMAF.ipynb",
          "examples/data_cmip5drs.py",
          "examples/data_cmip6drs.py",
          "examples/data_em.py",
          "examples/data_file.py",
          "examples/data_generic.py",
          "examples/data_obs.py",
          "examples/derived.py",
          "examples/ensemble.py",
          "examples/export.py",
          "examples/figarray.py",
          "examples/Gathering_my_results_in_an_html_page.html",
          "examples/Gathering_my_results_in_an_html_page.ipynb",
          "examples/Getting-started-with-plot-in-CliMAF.html",
          "examples/Getting-started-with-plot-in-CliMAF.ipynb",
          "examples/Getting-started-with-ts_plot.html",
          "examples/Getting-started-with-ts_plot.ipynb",
          "examples/ml2pl.py",
          "examples/my_2_outputs_script.sh",
          "examples/myscript_has_two_outputs.py",
          "examples/Playing_with_ensembles_from_scratch_last_hour_of_training_session_20181119.html",
          "examples/Playing_with_ensembles_from_scratch_last_hour_of_training_session_20181119.ipynb",
          "examples/plot_timeseries.py",
          "examples/plot_xsection.py",
          "examples/plotmap.py",
          "examples/README.rst",
          "examples/regrid.py",
          "examples/seaice.py",
          "examples/select_nicely.html",
          "examples/Working_with_CliMAF_ensembles.html",
          "examples/Working_with_CliMAF_ensembles.ipynb",
          "tools/angle.ncl",
          "tools/angle_data_CNRM.nc",
          'scripts/ml2pl',
      ],
      scripts=[
          'bin/climaf',
          'bin/exiv2',
          'bin/pdfcrop',
          'scripts/cdfsectionsm.sh',
          'scripts/cdfsections.sh',
          'scripts/cdftransport.sh',
          'scripts/cdftransp.sh',
          'scripts/clean_pdf.sh',
          'scripts/curl_tau_atm.jnl',
          'scripts/curves.ncl',
          'scripts/ensemble_time_series_plot.py',
          'scripts/gplot.ncl',
          'scripts/hovmoller.ncl',
          'scripts/ks.sh',
          'scripts/LinearRegression_UVCDAT.py',
          'scripts/mcdo_remote.py',
          'scripts/mcdo.sh',
          'scripts/mcdo_aux.sh',
          'scripts/mcdo.py',
          'scripts/mean_and_std.sh',
          'scripts/ml2pl.sh',
          'scripts/mtimavg.sh',
          'scripts/plot_cross_section.ncl',
          'scripts/plotmap.ncl',
          'scripts/read_ncks.sh',
          'scripts/regridll.sh',
          'scripts/regrid.sh',
          'scripts/time_average_basics.sh',
          'scripts/wcdo.sh',
      ],
      )
